# Required
version: 2

# Build documentation in the docs directory with Sphinx
sphinx:
  configuration: source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - htmlzip

# Specify the Python version
python:
  install:
    - requirements: requirements.txt

# Define how to install your project
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
